AlbertHeijnSynthesis/WebApp/Pages/AccessDenied.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebAppSynthesis.Pages
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

AlbertHeijnSynthesis/WebApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

AlbertHeijnSynthesis/WebApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            if (HttpContext.Session.GetString("cart")==null)
            {
                HttpContext.Session.SetString("cart","");
            }
           

        }
    }
}

AlbertHeijnSynthesis/WebApp/Pages/Login.cshtml.cs
using BusinessLayer;
using DBlayer;
using LogicLayer;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;
using WebAppSynthesis.DTO;

namespace WebAppSynthesis.Pages
{
    public class LoginModel : PageModel
    {
        PeopleManager peopleManager = new PeopleManager();
      
        public User user  { get; set; }
      

        [BindProperty]

        public LoginUserDTO loginUserDTO { get; set; }
        public void OnGet()
        {
        }
        public IActionResult OnPost()
        {
            if (ModelState.IsValid == true)
            {
                bool result = peopleManager.LoginUser(loginUserDTO.Username, loginUserDTO.Password);

                if (result)
                {
                    user = peopleManager.GetLoggedInUser(loginUserDTO.Username);
                    List<Claim> claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, loginUserDTO.Username),
                    new Claim("id", "" + user.Id)
                };




                    if (user != null)
                    {
                        claims.Add(new Claim(ClaimTypes.Role, "Customer"));
                    }
                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    HttpContext.SignInAsync(new ClaimsPrincipal(claimsIdentity));
                    if (user.UserRole.ToString() == "Customer")
                    {

                        return new RedirectToPageResult("/PersonalPage");
                    }
                    else if (user.UserRole.ToString() == "Employee")
                    {
                        return new RedirectToPageResult("/OnlyAdmin");

                    }



                }
            }
        
            return Page();

        }
    }
}

AlbertHeijnSynthesis/WebApp/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebAppSynthesis.Pages
{
    public class LogoutModel : PageModel
    {
        public async Task<IActionResult> OnGetAsync()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.SetString("cart", "");
            return RedirectToPage("/Index");

        }
    }
}

AlbertHeijnSynthesis/WebApp/Pages/MyAllOrders.cshtml.cs
using BusinessLayer;
using LogicLayer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using WebApp.DTO;

namespace WebApp.Pages
{
    public class MyAllOrdersModel : PageModel
    {
     
        OrderManager orderManager = new OrderManager();

        
        [BindProperty]

        public List<Order> orders { get; set; }

        public void OnGet( )
        {
            
                List<Order> filterOrders = orderManager.GetOrders().FindAll(x => x.User.Username == User.Identity.Name);

                orders = new List<Order>();
                foreach (Order order in filterOrders)
                {

                    orders.Add(order);
                }
            
       
            
          
        }
    }
}

AlbertHeijnSynthesis/WebApp/Pages/MyOrder.cshtml.cs
using BusinessLayer;
using EntitiesLayer;
using LogicLayer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Runtime.CompilerServices;
using WebApp.DTO;

namespace WebApp.Pages
{
    [Authorize(Policy = "OnlyUserAccess")]

    public class MyOrderModel : PageModel
    {
        PeopleManager peopleManager = new PeopleManager();
        ProductManager productManager = new ProductManager();
        OrderManager orderManager = new OrderManager();
        LocationManager locationManager = new LocationManager();
        [BindProperty]
        public List<Location> Locations { get; set; }
        [BindProperty]
        public List<Product> products { get; set; }
        [BindProperty]
        public List<Product> productsInCart { get; set; }
        
        [BindProperty]

        public List<Delivery> delivery { get; set; }
        [BindProperty]

        public List<Order> orders { get; set; }

        [BindProperty]

        public HomeDeliveryDTO homeDeliveryDTO { get; set; }
        [BindProperty]

        public PickupDeliveryDTO pickupDeliveryDTO { get; set; }
        public void OnGet()
        {
          
            Locations = locationManager.GetLocations();
            delivery = orderManager.GetAllDeliveries();
            orders = orderManager.GetOrders();

            productsInCart = new List<Product>();

            products = productManager.GetProducts();
            string listProduct = HttpContext.Session.GetString("cart");
            string[] myArray = listProduct.Split(',');
            foreach (var item in myArray)
            {
                int productId;
                if (int.TryParse(item, out productId))
                {
                    Product product = products.Find(x => x.Id == productId);
                    if (product != null)
                    {
                        productsInCart.Add(product);
                    }
                }
            }




        }
        public void  OnPostDelivery( )
        {
            if (!string.IsNullOrEmpty(homeDeliveryDTO.Hour.ToString()) & !string.IsNullOrEmpty(homeDeliveryDTO.Minutes) & !string.IsNullOrEmpty(homeDeliveryDTO.Address))
            {



                productsInCart = new List<Product>();

                products = productManager.GetProducts();
                string listProduct = HttpContext.Session.GetString("cart");
                string[] myArray = listProduct.Split(',');
                foreach (var item in myArray)
                {
                    productsInCart.Add(products.Find(x => x.Id == Convert.ToInt32(item)));


                }


                User user = peopleManager.GetLoggedInUser(User.Identity.Name);
                HomeDelivery homeDelivery = Mapper.MapToHomeDelivery(homeDeliveryDTO);

                Order neWorder = new Order(user, DateTime.Now, homeDelivery);
                foreach (var item in productsInCart)
                {
                    neWorder.AddProduct(item);
                }
                orderManager.AddOrder(neWorder);







                ViewData["Message"] = "Hello " + User.Identity.Name + " Your order successfully has been sent ";

               
            }
           
           
        }
        public void  OnPostPickup()
        {
            if (!string.IsNullOrEmpty(pickupDeliveryDTO.Hour.ToString()) & !string.IsNullOrEmpty(pickupDeliveryDTO.Minutes) & !string.IsNullOrEmpty(pickupDeliveryDTO.Location))
            {

                productsInCart = new List<Product>();

                products = productManager.GetProducts();
                string listProduct = HttpContext.Session.GetString("cart");
                string[] myArray = listProduct.Split(',');
                foreach (var item in myArray)
                {
                    productsInCart.Add(products.Find(x => x.Id == Convert.ToInt32(item)));





                }


                User user = peopleManager.GetLoggedInUser(User.Identity.Name);


                Location location = locationManager.GetLocations().Find(x => x.Address == pickupDeliveryDTO.Location);



                PickupDelivery pickupDelivery = Mapper.MapToPickupDelivery(pickupDeliveryDTO, location);

                Order neWorder = new Order(user, DateTime.Now, pickupDelivery);
                foreach (var item in productsInCart)
                {
                    neWorder.AddProduct(item);
                }
                orderManager.AddOrder(neWorder);




            

                ViewData["Message"] = "Hello " + User.Identity.Name + " Your order successfully has been sent ";
               
            }
         


           

        }
        public void OnPostDeleteProduct( int minus1)
        {
            productsInCart = new List<Product>();

            string listProduct = HttpContext.Session.GetString("cart");
            List<string> myArray = listProduct.Split(',').ToList();
            myArray.Remove(minus1.ToString());
            string a = "";
            foreach (var item in myArray)
            {
                if (a == "")
                {
                    a = item;
                }
                else
                {

                    a += "," + item;
                }

            }
            HttpContext.Session.Clear();
            HttpContext.Session.SetString("cart", a);

            OnGet();

        }

    }
}

AlbertHeijnSynthesis/WebApp/Pages/OnlyAdmin.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebAppSynthesis.Pages
{
   

    public class OnlyAdminModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

AlbertHeijnSynthesis/WebApp/Pages/PersonalPage.cshtml.cs
using BusinessLayer;
using LogicLayer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Security.Claims;

namespace WebAppSynthesis.Pages
{
    [Authorize(Policy = "OnlyUserAccess")]
    public class PersonalPageModel : PageModel
    {
        ProductManager productManager = new ProductManager();

        [BindProperty]
        public List<Product > products { get; set; }
     
        [BindProperty]

        public List<Product> cartProducts  { get; set; }
        public void OnGet()
        {
            //products = productManager.GetProducts().ToList();

            cartProducts = new List<Product>();
            if (products == null)
            {

                products = productManager.GetProducts().ToList();

            }
          

        }
         
        public void  OnPost(int idProduct) 
        {
              string listOfProducts = HttpContext.Session.GetString("cart");
                if (listOfProducts == "")
                {
                    listOfProducts += idProduct;
                    HttpContext.Session.SetString("cart", listOfProducts);
                }
                else
                {

                    listOfProducts += "," + idProduct;
                    HttpContext.Session.SetString("cart", listOfProducts);
                }
                products = productManager.GetProducts().ToList();
                OnGet();
           
         

        }
        public void OnPostMinus(int minus1)
        {
            string listProduct = HttpContext.Session.GetString("cart");
            List<string> myArray = listProduct.Split(',').ToList();
            myArray.Remove(minus1.ToString());
            string a = "";
            foreach (var item in myArray)
            {
                if (a == "")
                {
                    a = item;
                }
                else
                {

                    a += ","+item;
                }

            }
            HttpContext.Session.Clear();
            HttpContext.Session.SetString("cart", a);

            


            OnGet();

        }
        public void  OnPostFilter(string searchTerm)
        {
            products = productManager.filterProduct(searchTerm).ToList();

            OnGet();
        }
        public string getsubs(List<Category> list)
        {
            return string.Join(Environment.NewLine, list
                );
        }
    }

}

AlbertHeijnSynthesis/WebApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

AlbertHeijnSynthesis/WebApp/Pages/SignUp.cshtml.cs
using BusinessLayer;
using DBlayer;
using EntitiesLayer;
using LogicLayer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebAppSynthesis.DTO;

namespace WebAppSynthesis.Pages
{
    
    public class SignUpModel : PageModel
    {
        PeopleManager peopleManager = new PeopleManager();
        
        [BindProperty]

        public UserDTO userDTO { get; set; }
        public void OnGet()
        {

        }
        public IActionResult OnPost()
        {
           


            if (ModelState.IsValid == true)
            {
                User  savedUser = new User(userDTO.Name, userDTO.Surname, userDTO.Username, userDTO.Password,UserRole.Customer,"");
                peopleManager.AddUser(savedUser);
                
                    ViewData["Message"] = "Hello "   +   userDTO.Username   +  " Your account has been created ";


                }
                else
                {
                ViewData["Message"] = "Hello "   +   userDTO.Name   +  " username is already taken try again ";

                    return Page();
                }
               

               
                return new RedirectToPageResult("/Login");
            
            

        }
    }
}

AlbertHeijnSynthesis/WebApp/Pages/AccessDenied.cshtml
@page
@model WebAppSynthesis.Pages.AccessDeniedModel
@{
}
<h1>Access denied</h1>

AlbertHeijnSynthesis/WebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<div>
    @ViewData["Message"]
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    }
<div class="container">
    <h2>For this week ! for every week </h2>
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">

            <div class="item active">
                <img src="~/css/img/img1.jpg" alt="Gezond" style="width:100%;">
                <div class="carousel-caption">
                    <h3>Gezond</h3>
                    <p>LA is always so much fun!</p>
                </div>
            </div>

            <div class="item">
                <img src="~/css/img/img2.jpg" alt="Lekker" style="width:100%;">
                <div class="carousel-caption">
                    <h3>Lekker</h3>
                    <p>Thank you, Chicago!</p>
                </div>
            </div>

            <div class="item">
                <img src="~/css/img/img3.jpg" alt="Sterk" style="width:100%;">
                <div class="carousel-caption">
                    <h3>Sterk</h3>
                    <p>We love the Big Apple!</p>
                </div>
            </div>

        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

AlbertHeijnSynthesis/WebApp/Pages/Login.cshtml
@page
@model WebAppSynthesis.Pages.LoginModel
@{
    ViewData["Title"] = "Login page";

}


   
    <form class="form-horizontal" method="POST">
        <div class="form-group">
            <label class="control-label col-sm-2" for="username">Username:</label>
            <div class="col-sm-10">
            <input asp-for="loginUserDTO.Username " type="text" class="form-control" id="username" placeholder="Enter username">
            <span asp-validation-for="loginUserDTO.Username"></span>

            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="pwd">Password:</label>
            <div class="col-sm-10">
            <input asp-for="loginUserDTO.Password" type="password" class="form-control" id="pwd" placeholder="Enter your password">
            <span asp-validation-for="loginUserDTO.Password"></span>

            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <div class="checkbox">
                    <label><input type="checkbox"> Remember me</label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">Submit</button>
            </div>
        </div>
    </form>

    @section Scripts {
        <partial name="_ValidationScriptsPartial" />
    }

AlbertHeijnSynthesis/WebApp/Pages/Logout.cshtml
@page
@model WebAppSynthesis.Pages.LogoutModel
@{
}

AlbertHeijnSynthesis/WebApp/Pages/MyAllOrders.cshtml
@page
@model WebApp.Pages.MyAllOrdersModel
@{
}


<body>
<h1>Your Orders</h1>
<p> Your name is @User.Identity.Name</p>
<form method="POST">
    <div class="countainer">
        <table method="POST" class="table">
            <tr>
                    <th>order id </th>

                    <th>user </th>
                    <th>Product name</th>
                <th>Total price </th>
                <th>Date of order </th>
                <th>Delivery type </th>
                <th>Status </th>
               







            </tr>

@{
                   
                    foreach (var item in @Model.orders.OrderByDescending(x => x.DateOfOrder))
{
    string deliveryType = item.Delivery.GetType().Name;
    deliveryType = deliveryType.Replace("EntitiesLayer.", "");
    <tr>
                            <td>@item.Id</td>

        <td>@item.User.Username</td>
        <td>
            @{
                int count = 0;
                foreach (var product in item.Products)
                {
                    count++;
                    @product.Item
                    if (count < item.Products.Count())
                    {
                        @Html.Raw(",")
                    }
                }
            }
        </td>
        <td>@item.TotalPrice</td>
        <td>@item.DateOfOrder</td>
        <td>@deliveryType</td>
        <td>@item.Status</td>
    </tr>
}
}
               
</table>
</div>
</form>

    <div>
        @ViewData["Message"]
    </div>


    @section Scripts {
        <partial name="_ValidationScriptsPartial" />
    }
</body>

AlbertHeijnSynthesis/WebApp/Pages/MyOrder.cshtml
@page
@model WebApp.Pages.MyOrderModel
@{
}




<body>
<h1>Your Orders</h1>
<p> Your name is @User.Identity.Name</p>
    
    <div class="countainer">
        <table  class="table">
            <tr>
                <th>Product id</th>
            
                <th>Product name</th>
                <th>Product amount</th>
                <th>Product price</th>
                <th>Total price </th>              
                <th>Operation </th>
                

            </tr>

                @{
                    foreach (var item in @Model.productsInCart.Distinct()){
                  
                       
                    
                    <tr>


                        <td>  <input  type="text" value="@item.Id" id="" placeholder="@item.Id"> </td>
                        

                       

                        <td> <input  type="text" value="@item.Item" id="" placeholder="@item.Item">  </td>
                        

                            <td><input  value=@Model.productsInCart.Count(x => x.Id == item.Id) /> </td>
                       

                        <td><input  type="text" value="  @item.Price" id="" placeholder="@item.Item * @item.Amount">  </td>


                            <td> <input  value=@((@Model.productsInCart.Count(x=> x.Id == item.Id) * item.Price).ToString("0.00")) >  </td>

                          <td>
                        <form asp-page-handler="DeleteProduct" method="post">
                            <button type="submit" class="btn btn-default" name="minus1" value="@item.Id">Delete from cart</button>
                        </form>

                        </td>





                        </tr>
                    }
                }

           



            

        </table>
    </div>
 
    @{
        decimal total = 0;
        foreach (var item in Model.productsInCart)
            {
                total += item.Price;
                
            }
            <h1> total price : @total </h1>
    }

      



@*
           @*  /////////////////////////////////////////////////  *@
            <select id="state" name="state">
                <option value="">--- Please Select ---</option>
                <option value="nsw">Home delivery</option>
                <option value="qld">Pick up delivery</option>
            </select>

    <form asp-page-handler="Delivery" method="post" id="form-nsw" class="state-form" style="display:none;">
        <div>                       
            <label>select an hour</label><br>
            <select asp-for="  homeDeliveryDTO.Hour " >                          
            <span asp-validation-for=" homeDeliveryDTO.Hour"></span>
                    <option value="9">9</option>
                    <option value="10">10</option>
                    <option value="11">11</option>
                    <option value="12">12</option>
                    <option value="13">13</option>
                    <option value="14">14</option>
                    <option value="15">15</option>
                    <option value="16">16</option>
                    <option value="17">17</option>
                    <option value="18">18</option>
                    <option value="19">19</option>
                    <option value="20">20</option>
                    <option value="21">21</option>                           
            </select>
            <br>
            <label>between which period</label><br>
            <select asp-for=" homeDeliveryDTO.Minutes" >
            <span asp-validation-for=" homeDeliveryDTO.Minutes"></span>
                    <option value="between 00 and 15 minutes ">between 00 and 15 minutes</option>
                    <option value="between 15 minutes and 30 minutes">between 15 minutes and 30 minutes</option>
                    <option value="between 30 minutes and 45 inutes">between 30 minutes and 45 inutes</option>
                    <option value="between 45 minutes  and 00 minutes">between 45 minutes  and 00 minutes</option>
              
            </select>
            <br>
                
            <label>your address</label><br>
            <input asp-for=" homeDeliveryDTO.Address" type="text"  placeholder=" type your full address"><br>
            <span asp-validation-for=" homeDeliveryDTO.Address"></span>

        </div>
    
        <div class="col-sm-offset-2 col-sm-10">
            <button  type="submit" class="btn btn-default">Submit</button>
        </div>

    </form>
  

    <form asp-page-handler="Pickup" method="post" id="form-qld" class="state-form" style="display:none;">
        <div>                       
            <label>select an hour</label><br>
            <select asp-for="  pickupDeliveryDTO.Hour " >                          
            <span asp-validation-for=" pickupDeliveryDTO.Hour"></span>
                    <option value="8">8</option>                  
                    <option value="9">9</option>
                    <option value="10">10</option>
                    <option value="11">11</option>
                    <option value="12">12</option>
                    <option value="13">13</option>
                    <option value="14">14</option>
                    <option value="15">15</option>
                    <option value="16">16</option>
                    <option value="17">17</option>
                    <option value="18">18</option>
                    <option value="19">19</option>
                    <option value="20">20</option>
                    <option value="21">21</option>
                    <option value="22">22</option>
            </select>
            <br>
            <label>between which period</label><br>
            <select asp-for=" pickupDeliveryDTO.Minutes" >
            <span asp-validation-for=" pickupDeliveryDTO.Minutes"></span>
                    <option value="between 00 and 30 minutes ">between 00 and 30 minutes</option>
                    <option value="between 30 minutes and 00 minutes">between 30 minutes and 00 minutes</option>
                                            
            </select>

            <br>
            <label>select a location</label><br>
            <select asp-for="pickupDeliveryDTO.Location" >
            <span asp-validation-for=" pickupDeliveryDTO.Location"></span>
                       @foreach (var location in Model.Locations)
                           {
                               <optgroup label="City name">
                        <option value="@location.Address">@location.Name ->@location.Address</option>
                             </optgroup>
                        
                         }
            </select>

        </div>

        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Submit</button>
        </div>

    </form>
    <div>
        @ViewData["Message"]
    </div>
    @section Scripts {
            <partial name="_ValidationScriptsPartial" />
    }
        <script type="text/javascript">
    $("#state").change(function () {
        let state = this.value; //get state

        $('.state-form').hide(); //hide all forms

        $("#form-" + state).show(); //show only related form
    });
</script>

</body>

AlbertHeijnSynthesis/WebApp/Pages/OnlyAdmin.cshtml
@page
@model WebAppSynthesis.Pages.OnlyAdminModel
@{
}
<h1>Only Admin </h1>

AlbertHeijnSynthesis/WebApp/Pages/PersonalPage.cshtml
@page

@model WebAppSynthesis.Pages.PersonalPageModel
@{
   
}

<li><a asp-page="/MyAllOrders">View my orders</a></li>

<li><a asp-page="/MyOrder">View my cart</a></li>



<p> Your name is @User.Identity.Name</p>


<form  asp-page-handler="Filter"   method="post">

    <input type="text" name="searchTerm" />
    <button type="submit">Search</button>
</form><br>

<div class="countainer">
    <table method="GET" class="table" id="tblProducts">
        <tr>
            <th>Product id</th>
            <th>Product name</th>
            <th>Product unit</th>
            <th>Product price</th>
            <th>Category  </th>
            <th> Sub Category  </th>
          

          



        </tr>


        @{

            foreach (var item in Model.products)
            {
                <tr>


                    <td   value="@item.Id"> @item.Id   </td>
                    <td>@item.Item</td>
                    <td>@item.Unit</td>
                    <td>@item.Price</td>
                    <td>@item.Category.Name</td>
                    <td>
                        @foreach (var subCategory in item.Category.SubCategories)
                        {
                            <div>@subCategory.Name</div>
                        }
                    </td>


                    



                        <td>
                            <form  method="post"> 
                            <button type="submit" class="btn btn-default" name="idProduct" value="@item.Id">Add 1 to cart </button>
                            </form>
                            <form asp-page-handler="Minus" method="post">
                            <button type="submit" class="btn btn-default" name="minus1" value="@item.Id">Delete 1 from cart</button>
                            </form>

                        </td>


                    </tr>
            }
        }
        



        

    </table>
</div>